### ISSUE TITLE
Default Fedora 32 background missing from selection after f32-backgrounds-32.1.4 update

### ISSUE THREAD

**Issue by solgzr** [fedoradesign/backgrounds#23]
After updating to f32-backgrounds-32.1.4, the f32 default bg option disappeared from the selection grid. This is with GNOME de. If you select some other bg, then it's not possible to change back to the default f32 one, it's gone.

![Screenshot from 2020-04-28 14-02-08](https://user-images.githubusercontent.com/59263827/80480840-09a39980-895a-11ea-85de-9fc148ab45cb.png)

Downgrading the bg packages brings the f32 default bg back to the selection.

**Comment by frenkel** [comment]
I have this also. After resetting the corresponding keys with dconf, I do get the Fedora 32 background, but it appears different. It doesn't look like [this](https://9to5linux.com/fedora-32-beta-released-with-gnome-3-36-linux-kernel-5-6) anymore, but now appears like [this](https://www.root.cz/galerie/fedora-32/#0).

**Comment by areguera** [comment]
I can confirm this as well. After the f31->f32 upgrade the default f32 wallpaper isn't visible in backgrounds.

**Comment by luyatshimbalanga** [comment]
@jpenala @frenkel @areguera 
Could update to 32.2.0 to see if you can select the default background?

**Comment by areguera** [comment]
Hi @luyatshimbalanga, I've updated to 32.2.0 and f32 default background is not visible yet. The backgrounds looks like the following:

![image](https://user-images.githubusercontent.com/5214519/80921435-caf05380-8d4c-11ea-8d26-e8f2a386f278.png)

The installed packages are:
```
rpm -qa | grep f32-backgrounds
f32-backgrounds-gnome-32.2.0-1.fc32.noarch
f32-backgrounds-mate-32.2.0-1.fc32.noarch
f32-backgrounds-base-32.2.0-1.fc32.noarch
f32-backgrounds-xfce-32.2.0-1.fc32.noarch
f32-backgrounds-32.2.0-1.fc32.noarch
f32-backgrounds-kde-32.2.0-1.fc32.noarch
```

**Comment by luyatshimbalanga** [comment]
Hi @areguera 
What is inside `/usr/share/backgrounds/f32/default` ?

**Comment by gtms** [comment]
Hey @luyatshimbalanga, @areguera 

I am also having this issue, and here are the contents of my default backgrounds folder for f32:

```
$ ls -alh /usr/share/backgrounds/f32/default
total 68M
drwxr-xr-x   2 root           root     4.0k 2020-05-01 12:59 .
drwxr-xr-x   4 root           root     4.0k 2020-04-29 08:23 ..
-rwxr-xr-x   1 root           root      12M 2020-04-08 07:34 f32-01-dawn.png
-rwxr-xr-x   1 root           root      14M 2020-04-08 07:34 f32-02-day.png
-rwxr-xr-x   1 root           root      14M 2020-04-08 07:35 f32-03-dusk.png
-rwxr-xr-x   1 root           root      13M 2020-04-08 07:35 f32-04-twilight.png
-rw-r--r--   1 root           root     2.1k 2020-04-19 19:59 f32-animated.xml
-rw-r--r--   1 root           root      297 2020-04-21 02:51 f32-static.xml
-rwxr-xr-x   1 root           root      14M 2020-04-08 07:34 f32.png
lrwxrwxrwx   1 root           root       25 2020-04-29 08:23 f32.xml -> ../default/f32-static.xml
```

I've been having a peek at the repo, and what seems to be the default wallpaper is indeed not there in the 32.2 version. Let me know if you need some help to fix this . . .

**Comment by areguera** [comment]
I get this:
```
[al@nebula ~]$ tree /usr/share/backgrounds/f32/default
/usr/share/backgrounds/f32/default
├── f32.png
├── f32-static.xml
└── f32.xml -> ../default/f32-static.xml

0 directories, 3 files
```
and just in case it may be useful, the checksum of these files is:
```
[al@nebula ~]$ sha1sum /usr/share/backgrounds/f32/default/*
5d123dcb4aea7b8a1a02cf2bdd7bf6ab552ef310  /usr/share/backgrounds/f32/default/f32.png
b52d42c4989e5fa02b809d0e76b76fe1df8d3438  /usr/share/backgrounds/f32/default/f32-static.xml
b52d42c4989e5fa02b809d0e76b76fe1df8d3438  /usr/share/backgrounds/f32/default/f32.xml
```

**Comment by solgzr** [comment]
The issue is still there with 32.2.0

```
ls -a /usr/share/backgrounds/f32/default 

f32.png  f32-static.xml  f32.xml
```

**Comment by luyatshimbalanga** [comment]
@gtms @jpenala 
The default wallpaper is in indeed installed hence `f32.png` yet for some odd reasons background settings failed to see it.
Could you see what's inside `/usr/share/gnome-background-properties`?  "f32.xml" which allows the the selection of default background should be present. Same for "f32-animated.xml" and "f32-extras" for those who installed animated and extras backgrounds respectively.

**Comment by solgzr** [comment]
```

ls -a /usr/share/gnome-background-properties  

adwaita.xml  f32-animated.xml  f32.xml  fedora-workstation-backgrounds.xml
```
I haven't installed animated bg backage, but the animated xml is there for some reason.

f32.xml content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<wallpapers>
     <wallpaper deleted="false">
        <name>Fedora 32 Dawn</name>
        <filename>/usr/share/backgrounds/f32/default/f32-01-dawn.png</filename>
        <options>scaled</options>
        <shade_type>solid</shade_type>
        <pcolor>#3c6eb4</pcolor>
        <scolor>#294172</scolor>
    </wallpaper>

    <wallpaper deleted="false">
        <name>Fedora 32 Day Default</name>
        <filename>/usr/share/backgrounds/f32/default/f32-02-day.png</filename>
        <options>scaled</options>
        <shade_type>solid</shade_type>
        <pcolor>#3c6eb4</pcolor>
        <scolor>#294172</scolor>
    </wallpaper>
    
    <wallpaper deleted="false">
        <name>Fedora 32 Dusk</name>
        <filename>/usr/share/backgrounds/f32/default/f32-03-dusk.png</filename>
        <options>scaled</options>
        <shade_type>solid</shade_type>
        <pcolor>#3c6eb4</pcolor>
        <scolor>#294172</scolor>
    </wallpaper>

    <wallpaper deleted="false">
        <name>Fedora 32 Twilight</name>
        <filename>/usr/share/backgrounds/f32/default/f32-04-twilight.png</filename>
        <options>scaled</options>
        <shade_type>solid</shade_type>
        <pcolor>#3c6eb4</pcolor>
        <scolor>#294172</scolor>
    </wallpaper>

</wallpapers>
```

f32-animated.xml content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<wallpapers>
    <wallpaper deleted="false">
        <name>Fedora 32 Animated</name>
        <filename>/usr/share/backgrounds/f32/default/f32-animated.xml</filename>
        <options>scaled</options>
    </wallpaper>
</wallpapers>
```

**Comment by luyatshimbalanga** [comment]
@jpenala 
So the default background for Fedora 32 is installed yet background settings managed to avoid to see it. Can you reinstall the package and see if the background settings will look for them?

Alternatively, try to install with these updates not yet available on updates-testing repository:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1502553

**Comment by solgzr** [comment]
Upgrading to the latest koji pkg does not fix it. Only downgrading to 32.1.2. (which is icluded in f32 ISO) does. First non-working build is 32.1.3.

The difference in folder content:

32.1.2
![Screenshot from 2020-05-04 08-19-21](https://user-images.githubusercontent.com/59263827/80938305-41d72c00-8de1-11ea-8ce3-d041d257f69c.png)


32.2.0
![Screenshot from 2020-05-04 08-19-54](https://user-images.githubusercontent.com/59263827/80938317-4e5b8480-8de1-11ea-8c97-d9c411fa4007.png)

**Comment by luyatshimbalanga** [comment]
@jpenala 
Could you test this scratch build and see if that resolves the issue?
https://koji.fedoraproject.org/koji/taskinfo?taskID=44109111

**Comment by solgzr** [comment]
Yes, updating to **32.2.2** resolves the issue:

![Screenshot from 2020-05-05 08-39-59](https://user-images.githubusercontent.com/59263827/81037769-8b407d80-8eac-11ea-938f-63dad93167fb.png)

**Comment by solgzr** [comment]
As far as I'm concerned this issue is now resolved and seeing 32.2.2 is on its way to updates, I will close this issue. Thank you for your efforts!

**Comment by Elep331** [comment]
Hi, one small detail. Originally was in the right bottom corner inscription "Fedora". This is still missing.

**Comment by luyatshimbalanga** [comment]
@Elep331 
You will need an extension to display "Fedora" logo named "Background Logo" installed by default on Gnome session. Look for Extension application  (gnome-extensions-app as packaged)  to enable it assuming you are running Gnome.

**Comment by Elep331** [comment]
Ok, in this case, the extension has unusual behaviour. I have the extension active and the logo is not showing. It works only when I edit settings of this extension and set "Show for all backgrounds". Nevertheless, by default is this option off.

I tried it in a virtual machine on a fresh install of F32.

**Comment by maxborowsky** [comment]
@Elep331
Fedora logo by default is visible only if you select default wallpaper (f32.png for Fedora 32). It was also on previous versions, at least on the 29th, as far as I remember. And it has nothing to do with the f32-backgrounds package.
