### ISSUE TITLE
f37-backgrounds-37.0.2 installs broken symlinks

### ISSUE THREAD

**Issue by pacho2** [fedoradesign/backgrounds#43]
All these links end up broken:
```
# ls -l /usr/share/wallpapers/F37/contents/images_dark/
total 0
lrwxrwxrwx 1 root root 53 oct  2 11:04 1024x600.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1024x768.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1152x720.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1152x864.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1200x900.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1280x1024.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1280x720.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1280x768.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1280x800.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1280x960.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1366x768.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1440x1080.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1440x900.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1600x1200.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1600x1280.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1680x1050.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1920x1080.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1920x1200.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1920x1280.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 1920x1440.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 2048x1536.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 2160x1440.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 2304x1440.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 2560x1440.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 2560x1600.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 2960x1440.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 3000x2000.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 3200x1800.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 3440x1440.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 3840x2160.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 640x480.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 800x480.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
lrwxrwxrwx 1 root root 53 oct  2 11:04 800x600.webp -> ../../../../backgrounds/f37/default/f37-02-night.webp
```

**Comment by luyatshimbalanga** [comment]
The fix is available on [version 37.0.4](https://github.com/fedoradesign/backgrounds/releases/tag/v37.0.4). Closing this report as solved. Should the same issue occur, please reopen.

**Comment by pacho2** [comment]
I still get it for files under /usr/share/wallpapers/F37_light-blue/contents/images/:
```
lrwxrwxrwx 1 root root 49 oct 22 23:37 1024x600.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1024x768.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1152x720.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1152x864.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1200x900.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x1024.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x720.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x768.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x800.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x960.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1366x768.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1440x1080.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1440x900.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1600x1200.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1600x1280.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1680x1050.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1920x1080.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1920x1200.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1920x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2048x1536.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2160x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2304x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2560x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2560x1600.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2960x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 3000x2000.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 3200x1800.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 3440x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 3840x2160.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 640x480.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 800x480.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 800x600.png -> ../../../../backgrounds/f37/extras/light-blue.png
```
